apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
{{- include "labels" . | indent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
{{- include "labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{- include "labels" . | indent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.deployment.images.name }}
        ports:
        {{- range .Values.deployment.ports }}
        - containerPort: {{ . }}
        {{- end }}
