apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.hostname | quote }}
    http:
      paths:
      - pathType: Prefix
        path: {{ .Values.ingress.path | quote }}
        backend:
          service:
            name: {{ .Chart.Name }}-service
            port:
              number: {{ .Values.ingress.port }}
