apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
{{- include "labels" . | indent 4 }}
spec:
  selector:
{{- include "labels" . | indent 4 }}
  ports:
  {{- range .Values.ports }}
    - name: port-{{ . }}
      protocol: TCP
      port: {{ . }}
  {{- end }}