# Deployment
deployment:
  replicas: 2
  
  # Containers
  images:
    name: nginx
  ports:
    - 80

# Service
service:
  ports:
    - 80

# Ingress
ingress:
  hostname: app-1.k8s.local
  path: /
  port: 80